### ISSUE TITLE
$Palette variable doesn't match supplied value throwing errors.

### ISSUE THREAD

**Issue by tortilaman** [IBM-Design/colors#62]
After resolving #60 with my pull request #61, this error is thrown by every compiled scss file that imports `_ibm-colors.scss`,  regardless of whether or not the scss file actually uses any of the mixins from this library.

The first scss file that calls the color function calls it with `background: color('indigo', 70);`, so I'm confused where it's even getting `#ff0`, let alone how it's getting it in every file that gets compiled.

Here's the first of many similar errors.

```
ERROR in ./components/home/style.scss
Module build failed: ModuleBuildError: Module build failed: 
      @error $error-message;
     ^
      Color palette "#ff0" not found
      in /home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/src/style/mixins/_ibm-colors.scss (line 52, column 7)
    at runLoaders (/home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/webpack/lib/NormalModule.js:192:19)
    at /home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/sass-loader/node_modules/async/dist/async.js:2243:31)
    at Object.callback (/home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/sass-loader/node_modules/async/dist/async.js:906:16)
    at options.error (/home/pipeline/7c29663d-e681-44c7-952e-8edee6d2bef9/node_modules/node-sass/lib/index.js:294:32)
 @ ./components/home/index.js 12:13-36
 @ ./components/app.js
 @ ./index.js
```

Any help would be much appreciated, at this point I'm stumped.

**Comment by seejamescode** [comment]
Hi @tortilaman, did you find a solution?

I saw [this comment](https://github.com/IBM-Design/colors/pull/61#issuecomment-308885849) and could not tell if it came before or after this issue.
